import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import SubscribeCard from "@/components/homepageComponents/subscribeCard/SubscribeCard";
import { RecipeProvider } from "@/context/ReciepContext";
import "@/style/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecipeProvider>
          <Header/>
          {children}
          <SubscribeCard/>
          <Footer/>
        </RecipeProvider>
       
      </body>
    </html>
  );
}
